### PR TITLE
Add system test support

### PR DESCRIPTION
**Pull request by brettle**

### CODE REVIEW

**Comment by brettle** [comment]
@CoolSpy3, hold off on reviewing this. I just realized I did it wrong and what I thought was success was a false positivie.

**Comment by brettle** [comment]
@CoolSpy3, should be fixed now.

**Comment by brettle** [comment]
Ok, @CoolSpy3 , I think this is *finally* ready for review.

**Comment by CoolSpy3** [comment]
@brettle I'm running into a problem building your PR. When trying to run the example project, the `systemTest` task hangs indefinitely :/ Here's the build log.
```PS A:\FRC\2021\WebotsWebSocketsImpl> ./gradlew build

> Task :licenseReport
Wrote HTML report to file:///A:/FRC/2021/WebotsWebSocketsImpl/build/reports/licenses/licenseReport.html.
Wrote JSON report to file:///A:/FRC/2021/WebotsWebSocketsImpl/build/reports/licenses/licenseReport.json.
HAL Extensions: Attempting to load: halsim_gui
Simulator GUI Initializing.
Simulator GUI Initialized!
HAL Extensions: Successfully loaded extension       
HAL Extensions: Attempting to load: halsim_ds_socket
DriverStationSocket Initializing.
DriverStationSocket Initialized!
HAL Extensions: Successfully loaded extension
HAL Extensions: Attempting to load: halsim_ws_server
Websocket WS Server Initializing.
Listening at http://localhost:3300
WebSocket URI: /wpilibws
Websocket WS Server Initialized!
HAL Extensions: Successfully loaded extension
********** Robot program starting **********
Telling WebotsSupervisor that we're ready
Waiting for WebotsSupervisor to be ready

> Task :example:systemTest
If you receive errors loading the JNI dependencies, make sure you have the latest Visual Studio C++ Redstributable installed.
That can be found at https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Waiting for simulation to finish...
<==========---> 82% EXECUTING [5m 23s]
> :example:systemTest
> IDLE```

**Comment by brettle** [comment]
You need to be running Webots with the world in the example open.

--Dean

**Review by CoolSpy3 — APPROVED** [review]
Can confirm this fixes the issue. Running Webots should probably be documented somewhere. Also, note that the example project is configured for Java 11 which will prevent it from being built by people using only Java 8.

**Pull request merged**
