### PR TITLE
Use correct main class  remove unneeded lauchers.

### PR DESCRIPTION
**Pull request by brettle**

### CODE REVIEW

**Comment by CoolSpy3** [comment]
The current version of the code is designed as a Webots controller and the build.gradle has been modified to not run as a standalone application. Should we consider either removing all launch configurations or altering the build.gradle to readd standalone functionality?

**Comment by brettle** [comment]
> The current version of the code is designed as a Webots controller and the build.gradle has been modified to not run as a standalone application. Should we consider either removing all launch configurations or altering the build.gradle to readd standalone functionality?

A Webots controller *is* a standalone application jar. If it is located in a subfolder of ".../controllers", and has a name matching the subfolder name, and contains a main class with a name matching the subfolder name, and the .wbt names it as a controller of a Robot node, then Webots will automatically launch that application to control the robot. However, the same jar can be launched from vscode to control the robot if the .wbt says the controller is named "<extern>". That second configuration can be very useful for debugging, which is what this change is designed to support.

**Review by CoolSpy3 — APPROVED** [review]

**Comment by brettle** [comment]
I really don't like copying all the dlls into the project dir. Can you try adding the native lib dirs to your PATH and relaunching VSCode to see if that obviates the need to do that?

Should dirs should be:
 - $WEBOTS_HOME/lib/controller
 - $WEBOTS_HOME/msys64/mingw64/bin
 - $WEBOTS_HOME/msys64/mingw64/bin/cpp

where $WEBOTS_HOME is where you've installed Webots (either $USER_HOME/Webots or $LOCALAPPDATA//Programs/Webots).

**Comment by CoolSpy3** [comment]
Can confirm this works, but do we want to have all users of the standalone version edit their environment vars?

**Comment by brettle** [comment]
> Can confirm this works, but do we want to have all users of the standalone version edit their environment vars?

Only folks who want to debug the controller need edit their env var, not all users. Most users will just use the controller as a non-extern controller. 

I'd prefer to make avoidance of manual env var setting a separate issue. I've created  #17 to cover it.

**Review by CoolSpy3 — APPROVED** [review]

**Pull request merged**
